logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: ${DB_URL}
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: selfsigned_localhost_sslserver
  port: 8443
